import { NextRequest, NextResponse } from "next/server";
import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/auth";
import { db } from "@/lib/db";

// Delete all auto-generated health records for a livestock entry
export async function DELETE(
  request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    const session = await getServerSession(authOptions);
    if (!session?.user?.id) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    const { id: livestockEntryId } = await params;

    // Verify ownership
    const entry = await db.livestockEntry.findFirst({
      where: { id: livestockEntryId, userId: session.user.id },
    });

    if (!entry) {
      return NextResponse.json({ error: "Livestock not found" }, { status: 404 });
    }

    // Delete all auto-generated health records
    const result = await db.healthRecord.deleteMany({
      where: {
        livestockEntryId,
        isAutoGenerated: true,
      },
    });

    return NextResponse.json({
      success: true,
      deletedCount: result.count,
    });
  } catch (error) {
    console.error("Error deleting auto-generated health records:", error);
    return NextResponse.json(
      { error: "Failed to delete records" },
      { status: 500 }
    );
  }
}
