"use client";

import { useState, useEffect, use } from "react";
import Link from "next/link";
import {
  ArrowLeft,
  Plus,
  Loader2,
  Syringe,
  Pill,
  Stethoscope,
  AlertTriangle,
  Heart,
  Trash2,
  RefreshCw,
  MoreVertical,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Spinner } from "@/components/ui/spinner";

const RECORD_TYPES = [
  { value: "VACCINATION", label: "Vaccination", icon: Syringe },
  { value: "DEWORMING", label: "Deworming", icon: Pill },
  { value: "DISEASE", label: "Disease/Illness", icon: AlertTriangle },
  { value: "TREATMENT", label: "Treatment", icon: Stethoscope },
  { value: "VETERINARY_VISIT", label: "Veterinary Visit", icon: Heart },
  { value: "MORTALITY", label: "Mortality", icon: AlertTriangle },
];

interface HealthRecord {
  id: string;
  type: string;
  status: "PENDING" | "COMPLETED" | "SKIPPED" | "OVERDUE";
  date: string;
  completedDate: string | null;
  vaccineName: string | null;
  diagnosis: string | null;
  treatment: string | null;
  medication: string | null;
  cost: number | null;
  notes: string | null;
  isAutoGenerated: boolean;
}

const STATUS_COLORS: Record<string, string> = {
  PENDING: "bg-yellow-100 text-yellow-700 border-yellow-200",
  COMPLETED: "bg-green-100 text-green-700 border-green-200",
  SKIPPED: "bg-gray-100 text-gray-700 border-gray-200",
  OVERDUE: "bg-red-100 text-red-700 border-red-200",
};

export default function LivestockHealthPage({
  params,
}: {
  params: Promise<{ id: string }>;
}) {
  const { id } = use(params);
  const [records, setRecords] = useState<HealthRecord[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [isAdding, setIsAdding] = useState(false);
  const [showForm, setShowForm] = useState(false);
  const [isRegenerating, setIsRegenerating] = useState(false);
  const [isDeletingAll, setIsDeletingAll] = useState(false);
  const [showActions, setShowActions] = useState(false);
  const [formData, setFormData] = useState({
    type: "VACCINATION",
    date: new Date().toISOString().split("T")[0],
    vaccineName: "",
    diagnosis: "",
    treatment: "",
    medication: "",
    cost: "",
    notes: "",
  });

  useEffect(() => {
    fetchRecords();
  }, [id]);

  async function fetchRecords() {
    try {
      const res = await fetch(`/api/livestock/${id}/health`);
      if (res.ok) {
        const data = await res.json();
        setRecords(data);
      }
    } catch (error) {
      console.error("Failed to fetch records");
    } finally {
      setIsLoading(false);
    }
  }

  async function handleSubmit(e: React.FormEvent) {
    e.preventDefault();
    setIsAdding(true);

    try {
      const res = await fetch(`/api/livestock/${id}/health`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          ...formData,
          cost: formData.cost ? parseFloat(formData.cost) : undefined,
        }),
      });

      if (res.ok) {
        const newRecord = await res.json();
        setRecords([newRecord, ...records]);
        setShowForm(false);
        setFormData({
          type: "VACCINATION",
          date: new Date().toISOString().split("T")[0],
          vaccineName: "",
          diagnosis: "",
          treatment: "",
          medication: "",
          cost: "",
          notes: "",
        });
      }
    } catch (error) {
      console.error("Failed to add record");
    } finally {
      setIsAdding(false);
    }
  }

  const getRecordIcon = (type: string) => {
    const record = RECORD_TYPES.find((r) => r.value === type);
    return record?.icon || Heart;
  };

  const getRecordLabel = (type: string) => {
    const record = RECORD_TYPES.find((r) => r.value === type);
    return record?.label || type;
  };

  async function updateRecordStatus(recordId: string, newStatus: string) {
    try {
      const res = await fetch(`/api/livestock/health-records/${recordId}`, {
        method: "PATCH",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ status: newStatus }),
      });

      if (res.ok) {
        setRecords(records.map(r => 
          r.id === recordId 
            ? { ...r, status: newStatus as HealthRecord["status"], completedDate: newStatus === "COMPLETED" ? new Date().toISOString() : null }
            : r
        ));
      }
    } catch (error) {
      console.error("Failed to update status");
    }
  }

  async function handleDeleteAllAutoGenerated() {
    if (!confirm("Are you sure you want to delete all auto-generated health records? This cannot be undone.")) {
      return;
    }

    setIsDeletingAll(true);
    try {
      const res = await fetch(`/api/livestock/${id}/health/auto-generated`, {
        method: "DELETE",
      });

      if (res.ok) {
        fetchRecords();
      }
    } catch (error) {
      console.error("Failed to delete records");
    } finally {
      setIsDeletingAll(false);
      setShowActions(false);
    }
  }

  async function handleRegenerateRecords() {
    if (!confirm("This will generate new health records based on the animal type. Continue?")) {
      return;
    }

    setIsRegenerating(true);
    try {
      const res = await fetch(`/api/livestock/${id}/health/regenerate`, {
        method: "POST",
      });

      if (res.ok) {
        fetchRecords();
      }
    } catch (error) {
      console.error("Failed to regenerate records");
    } finally {
      setIsRegenerating(false);
      setShowActions(false);
    }
  }

  // Check for overdue records
  const processedRecords = records.map(record => {
    if (record.status === "PENDING" && new Date(record.date) < new Date()) {
      return { ...record, status: "OVERDUE" as const };
    }
    return record;
  });

  if (isLoading) {
    return (
      <div className="flex justify-center py-12">
        <Spinner size="lg" />
      </div>
    );
  }

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-4">
          <Button variant="ghost" size="icon" asChild>
            <Link href={`/dashboard/livestock/${id}`}>
              <ArrowLeft className="h-5 w-5" />
            </Link>
          </Button>
          <h1 className="text-2xl font-bold">Health Records</h1>
        </div>
        <div className="flex items-center gap-2">
          {/* Actions Dropdown */}
          <div className="relative">
            <Button
              variant="outline"
              size="sm"
              onClick={() => setShowActions(!showActions)}
            >
              <MoreVertical className="h-4 w-4 mr-1" />
              Actions
            </Button>
            {showActions && (
              <div className="absolute right-0 mt-2 w-56 bg-white border rounded-lg shadow-lg z-10">
                <button
                  onClick={handleRegenerateRecords}
                  disabled={isRegenerating}
                  className="w-full flex items-center gap-2 px-4 py-2 text-sm text-left hover:bg-gray-50 disabled:opacity-50"
                >
                  <RefreshCw className={`h-4 w-4 ${isRegenerating ? "animate-spin" : ""}`} />
                  {isRegenerating ? "Regenerating..." : "Regenerate Health Records"}
                </button>
                <button
                  onClick={handleDeleteAllAutoGenerated}
                  disabled={isDeletingAll}
                  className="w-full flex items-center gap-2 px-4 py-2 text-sm text-left text-red-600 hover:bg-red-50 disabled:opacity-50"
                >
                  <Trash2 className="h-4 w-4" />
                  {isDeletingAll ? "Deleting..." : "Delete Auto-Generated Records"}
                </button>
              </div>
            )}
          </div>
          <Button onClick={() => setShowForm(!showForm)}>
            <Plus className="h-4 w-4 mr-2" />
            Add Record
          </Button>
        </div>
      </div>

      {showForm && (
        <Card>
          <CardHeader>
            <CardTitle>New Health Record</CardTitle>
          </CardHeader>
          <CardContent>
            <form onSubmit={handleSubmit} className="space-y-4">
              <div className="grid grid-cols-2 gap-4">
                <div className="space-y-2">
                  <Label htmlFor="type">Record Type</Label>
                  <select
                    id="type"
                    value={formData.type}
                    onChange={(e) => setFormData({ ...formData, type: e.target.value })}
                    className="w-full px-3 py-2 rounded-md border bg-background"
                  >
                    {RECORD_TYPES.map((type) => (
                      <option key={type.value} value={type.value}>
                        {type.label}
                      </option>
                    ))}
                  </select>
                </div>
                <div className="space-y-2">
                  <Label htmlFor="date">Date</Label>
                  <Input
                    id="date"
                    type="date"
                    value={formData.date}
                    onChange={(e) => setFormData({ ...formData, date: e.target.value })}
                    required
                  />
                </div>
              </div>

              {formData.type === "VACCINATION" && (
                <div className="space-y-2">
                  <Label htmlFor="vaccineName">Vaccine Name</Label>
                  <Input
                    id="vaccineName"
                    value={formData.vaccineName}
                    onChange={(e) => setFormData({ ...formData, vaccineName: e.target.value })}
                    placeholder="e.g., Newcastle Disease Vaccine"
                  />
                </div>
              )}

              {(formData.type === "DISEASE" || formData.type === "TREATMENT") && (
                <>
                  <div className="space-y-2">
                    <Label htmlFor="diagnosis">Diagnosis</Label>
                    <Input
                      id="diagnosis"
                      value={formData.diagnosis}
                      onChange={(e) => setFormData({ ...formData, diagnosis: e.target.value })}
                      placeholder="What was diagnosed?"
                    />
                  </div>
                  <div className="space-y-2">
                    <Label htmlFor="treatment">Treatment</Label>
                    <Input
                      id="treatment"
                      value={formData.treatment}
                      onChange={(e) => setFormData({ ...formData, treatment: e.target.value })}
                      placeholder="Treatment given"
                    />
                  </div>
                  <div className="space-y-2">
                    <Label htmlFor="medication">Medication</Label>
                    <Input
                      id="medication"
                      value={formData.medication}
                      onChange={(e) => setFormData({ ...formData, medication: e.target.value })}
                      placeholder="Medication administered"
                    />
                  </div>
                </>
              )}

              <div className="grid grid-cols-2 gap-4">
                <div className="space-y-2">
                  <Label htmlFor="cost">Cost (GHS)</Label>
                  <Input
                    id="cost"
                    type="number"
                    step="0.01"
                    value={formData.cost}
                    onChange={(e) => setFormData({ ...formData, cost: e.target.value })}
                    placeholder="0.00"
                  />
                </div>
              </div>

              <div className="space-y-2">
                <Label htmlFor="notes">Notes</Label>
                <textarea
                  id="notes"
                  value={formData.notes}
                  onChange={(e) => setFormData({ ...formData, notes: e.target.value })}
                  className="w-full min-h-[80px] px-3 py-2 rounded-md border bg-background"
                  placeholder="Additional details..."
                />
              </div>

              <div className="flex gap-2">
                <Button type="button" variant="outline" onClick={() => setShowForm(false)}>
                  Cancel
                </Button>
                <Button type="submit" disabled={isAdding}>
                  {isAdding && <Loader2 className="h-4 w-4 mr-2 animate-spin" />}
                  Save Record
                </Button>
              </div>
            </form>
          </CardContent>
        </Card>
      )}

      <Card>
        <CardHeader>
          <CardTitle>Health History</CardTitle>
        </CardHeader>
        <CardContent>
          {processedRecords.length === 0 ? (
            <p className="text-gray-500 text-center py-8">
              No health records yet. Click "Add Record" to log vaccinations, treatments, etc.
            </p>
          ) : (
            <div className="space-y-3">
              {processedRecords.map((record) => {
                const Icon = getRecordIcon(record.type);
                return (
                  <div
                    key={record.id}
                    className={`flex items-start gap-3 p-3 rounded-lg border ${
                      record.status === "COMPLETED" 
                        ? "bg-green-50 border-green-200" 
                        : record.status === "OVERDUE"
                        ? "bg-red-50 border-red-200"
                        : record.status === "SKIPPED"
                        ? "bg-gray-50 border-gray-200"
                        : "bg-yellow-50 border-yellow-200"
                    }`}
                  >
                    <div className={`h-10 w-10 rounded-full flex items-center justify-center border ${
                      record.type === "MORTALITY" ? "bg-red-50" : "bg-white"
                    }`}>
                      <Icon className={`h-5 w-5 ${
                        record.type === "MORTALITY" ? "text-red-500" : "text-primary"
                      }`} />
                    </div>
                    <div className="flex-1">
                      <div className="flex items-center justify-between mb-1">
                        <div className="flex items-center gap-2">
                          <p className="font-medium">{getRecordLabel(record.type)}</p>
                          {record.isAutoGenerated && (
                            <span className="text-xs px-1.5 py-0.5 bg-purple-100 text-purple-700 rounded">
                              Auto-scheduled
                            </span>
                          )}
                        </div>
                        <div className="flex items-center gap-2">
                          <span className={`text-xs px-2 py-1 rounded-full border ${STATUS_COLORS[record.status]}`}>
                            {record.status}
                          </span>
                        </div>
                      </div>
                      <p className="text-sm text-gray-500 mb-2">
                        Due: {new Date(record.date).toLocaleDateString()}
                        {record.completedDate && (
                          <span className="ml-2 text-green-600">
                            • Completed: {new Date(record.completedDate).toLocaleDateString()}
                          </span>
                        )}
                      </p>
                      {record.vaccineName && (
                        <p className="text-sm text-gray-600">Vaccine: {record.vaccineName}</p>
                      )}
                      {record.diagnosis && (
                        <p className="text-sm text-gray-600">Diagnosis: {record.diagnosis}</p>
                      )}
                      {record.treatment && (
                        <p className="text-sm text-gray-600">Treatment: {record.treatment}</p>
                      )}
                      {record.notes && (
                        <p className="text-sm text-gray-500 mt-1 line-clamp-2">{record.notes}</p>
                      )}
                      {record.cost && (
                        <p className="text-sm text-gray-500">
                          Cost: GHS {record.cost.toLocaleString()}
                        </p>
                      )}
                      
                      {/* Status Toggle Buttons */}
                      {record.status !== "COMPLETED" && (
                        <div className="flex gap-2 mt-3 pt-3 border-t">
                          <button
                            onClick={() => updateRecordStatus(record.id, "COMPLETED")}
                            className="text-xs px-3 py-1.5 bg-green-600 text-white rounded hover:bg-green-700"
                          >
                            ✓ Mark Complete
                          </button>
                          {record.status !== "SKIPPED" && (
                            <button
                              onClick={() => updateRecordStatus(record.id, "SKIPPED")}
                              className="text-xs px-3 py-1.5 bg-gray-500 text-white rounded hover:bg-gray-600"
                            >
                              Skip
                            </button>
                          )}
                        </div>
                      )}
                      {record.status === "COMPLETED" && (
                        <div className="flex gap-2 mt-3 pt-3 border-t">
                          <button
                            onClick={() => updateRecordStatus(record.id, "PENDING")}
                            className="text-xs px-3 py-1.5 bg-yellow-500 text-white rounded hover:bg-yellow-600"
                          >
                            Mark as Pending
                          </button>
                        </div>
                      )}
                    </div>
                  </div>
                );
              })}
            </div>
          )}
        </CardContent>
      </Card>
    </div>
  );
}
