"use client";

import { useState, useEffect, useMemo } from "react";
import Link from "next/link";
import {
  Plus,
  Calendar,
  CheckCircle2,
  Circle,
  Clock,
  AlertCircle,
  Trash2,
  Filter,
  RefreshCw,
  ChevronLeft,
  ChevronRight,
  List,
  CalendarDays,
  Wheat,
  Beef,
  Fish,
  LayoutGrid,
  ArrowRight,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Spinner } from "@/components/ui/spinner";

interface Task {
  id: string;
  title: string;
  description: string | null;
  dueDate: string;
  category: string;
  priority: string;
  status: string;
  completedAt: string | null;
  isAutoGenerated: boolean;
  sourceType: string | null;
  relatedType: string | null;
  relatedId: string | null;
}

interface BatchTask {
  id: string;
  title: string;
  dueDate: string;
  priority: string;
  status: string;
}

interface Batch {
  id: string;
  type: "crop" | "livestock" | "aquaculture";
  name: string;
  plotName?: string;
  batchName?: string;
  fishSpecies?: string;
  farmName?: string;
  quantity?: number;
  status: string;
  plantingDate?: string;
  expectedHarvestDate?: string;
  totalTasks: number;
  pendingTasks: number;
  completedTasks: number;
  overdueTasks: number;
  upcomingTasks: BatchTask[];
  progress: number;
}

const CATEGORIES = [
  { value: "", label: "All Categories" },
  { value: "CROP", label: "🌾 Crop Activities" },
  { value: "LIVESTOCK", label: "🐄 Livestock Activities" },
  { value: "AQUACULTURE", label: "🐟 Aquaculture" },
  { value: "FINANCIAL", label: "💰 Financial" },
  { value: "GENERAL", label: "📋 General" },
];

const STATUS_FILTERS = [
  { value: "", label: "All" },
  { value: "PENDING", label: "Pending" },
  { value: "IN_PROGRESS", label: "In Progress" },
  { value: "COMPLETED", label: "Completed" },
];

const PRIORITY_COLORS: Record<string, string> = {
  LOW: "bg-gray-100 text-gray-700",
  MEDIUM: "bg-blue-100 text-blue-700",
  HIGH: "bg-orange-100 text-orange-700",
  URGENT: "bg-red-100 text-red-700",
};

const STATUS_ICONS: Record<string, React.ReactNode> = {
  PENDING: <Circle className="h-4 w-4 text-gray-400" />,
  IN_PROGRESS: <Clock className="h-4 w-4 text-blue-500" />,
  COMPLETED: <CheckCircle2 className="h-4 w-4 text-green-500" />,
  CANCELLED: <AlertCircle className="h-4 w-4 text-red-500" />,
};

export default function TasksPage() {
  const [tasks, setTasks] = useState<Task[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState("");
  const [statusFilter, setStatusFilter] = useState("");
  const [categoryFilter, setCategoryFilter] = useState("");
  const [isGenerating, setIsGenerating] = useState(false);
  const [generateMessage, setGenerateMessage] = useState("");
  const [viewMode, setViewMode] = useState<"batches" | "list" | "calendar">("batches");
  const [currentMonth, setCurrentMonth] = useState(new Date());
  const [batches, setBatches] = useState<{
    crops: Batch[];
    livestock: Batch[];
    aquaculture: Batch[];
    summary: { totalBatches: number; totalPending: number; totalOverdue: number; totalCompleted: number };
  } | null>(null);
  const [selectedBatch, setSelectedBatch] = useState<Batch | null>(null);

  useEffect(() => {
    if (viewMode === "batches") {
      fetchBatches();
    } else {
      fetchTasks();
    }
  }, [statusFilter, categoryFilter, viewMode]);

  async function fetchBatches() {
    setIsLoading(true);
    try {
      const response = await fetch("/api/tasks/batches");
      if (!response.ok) throw new Error("Failed to fetch batches");
      const data = await response.json();
      setBatches(data);
    } catch (err) {
      setError("Failed to load task batches");
    } finally {
      setIsLoading(false);
    }
  }

  async function generateTasksForExisting() {
    setIsGenerating(true);
    setGenerateMessage("");
    try {
      const response = await fetch("/api/tasks/generate", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ type: "all" }),
      });
      
      if (!response.ok) throw new Error("Failed to generate tasks");
      
      const data = await response.json();
      setGenerateMessage(`Generated ${data.totalTasksGenerated} tasks for ${data.entries.length} entries`);
      fetchTasks(); // Refresh the task list
    } catch (err) {
      setError("Failed to generate tasks");
    } finally {
      setIsGenerating(false);
    }
  }

  async function fetchTasks() {
    setIsLoading(true);
    try {
      const params = new URLSearchParams();
      if (statusFilter) params.append("status", statusFilter);
      if (categoryFilter) params.append("category", categoryFilter);

      const response = await fetch(`/api/tasks?${params.toString()}`);
      if (!response.ok) throw new Error("Failed to fetch tasks");
      const data = await response.json();
      setTasks(data);
    } catch (err) {
      setError("Failed to load tasks");
    } finally {
      setIsLoading(false);
    }
  }

  async function updateTaskStatus(taskId: string, status: string) {
    try {
      const response = await fetch(`/api/tasks/${taskId}`, {
        method: "PATCH",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ status }),
      });

      if (!response.ok) throw new Error("Failed to update task");
      fetchTasks();
    } catch (err) {
      setError("Failed to update task");
    }
  }

  async function deleteTask(taskId: string) {
    if (!confirm("Are you sure you want to delete this task?")) return;

    try {
      const response = await fetch(`/api/tasks/${taskId}`, {
        method: "DELETE",
      });

      if (!response.ok) throw new Error("Failed to delete task");
      setTasks(tasks.filter((t) => t.id !== taskId));
    } catch (err) {
      setError("Failed to delete task");
    }
  }

  function isOverdue(dueDate: string, status: string) {
    if (status === "COMPLETED" || status === "CANCELLED") return false;
    return new Date(dueDate) < new Date();
  }

  function formatDate(dateString: string) {
    const date = new Date(dateString);
    const today = new Date();
    const tomorrow = new Date(today);
    tomorrow.setDate(tomorrow.getDate() + 1);

    if (date.toDateString() === today.toDateString()) return "Today";
    if (date.toDateString() === tomorrow.toDateString()) return "Tomorrow";

    return date.toLocaleDateString("en-GB", {
      day: "numeric",
      month: "short",
      year: date.getFullYear() !== today.getFullYear() ? "numeric" : undefined,
    });
  }

  // Group tasks by status
  const pendingTasks = tasks.filter((t) => t.status === "PENDING");
  const inProgressTasks = tasks.filter((t) => t.status === "IN_PROGRESS");
  const completedTasks = tasks.filter((t) => t.status === "COMPLETED");

  // Calendar helpers
  const calendarDays = useMemo(() => {
    const year = currentMonth.getFullYear();
    const month = currentMonth.getMonth();
    const firstDay = new Date(year, month, 1);
    const lastDay = new Date(year, month + 1, 0);
    const startPadding = firstDay.getDay();
    const days: (Date | null)[] = [];
    
    for (let i = 0; i < startPadding; i++) {
      days.push(null);
    }
    for (let i = 1; i <= lastDay.getDate(); i++) {
      days.push(new Date(year, month, i));
    }
    return days;
  }, [currentMonth]);

  const tasksByDate = useMemo(() => {
    const map = new Map<string, Task[]>();
    tasks.forEach((task) => {
      const dateKey = new Date(task.dueDate).toDateString();
      if (!map.has(dateKey)) {
        map.set(dateKey, []);
      }
      map.get(dateKey)!.push(task);
    });
    return map;
  }, [tasks]);

  function prevMonth() {
    setCurrentMonth(new Date(currentMonth.getFullYear(), currentMonth.getMonth() - 1, 1));
  }

  function nextMonth() {
    setCurrentMonth(new Date(currentMonth.getFullYear(), currentMonth.getMonth() + 1, 1));
  }

  if (isLoading) {
    return (
      <div className="flex items-center justify-center h-64">
        <Spinner size="lg" />
      </div>
    );
  }

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-3xl font-bold text-gray-900">Tasks</h1>
          <p className="text-gray-600">Manage your farm activities and tasks</p>
        </div>
        <div className="flex gap-2">
          <div className="flex border rounded-lg overflow-hidden">
            <button
              onClick={() => setViewMode("batches")}
              className={`px-3 py-2 flex items-center gap-1 text-sm ${
                viewMode === "batches" ? "bg-primary text-white" : "bg-white hover:bg-gray-50"
              }`}
            >
              <LayoutGrid className="h-4 w-4" />
              Batches
            </button>
            <button
              onClick={() => setViewMode("list")}
              className={`px-3 py-2 flex items-center gap-1 text-sm ${
                viewMode === "list" ? "bg-primary text-white" : "bg-white hover:bg-gray-50"
              }`}
            >
              <List className="h-4 w-4" />
              List
            </button>
            <button
              onClick={() => setViewMode("calendar")}
              className={`px-3 py-2 flex items-center gap-1 text-sm ${
                viewMode === "calendar" ? "bg-primary text-white" : "bg-white hover:bg-gray-50"
              }`}
            >
              <CalendarDays className="h-4 w-4" />
              Calendar
            </button>
          </div>
          <Button 
            variant="outline" 
            onClick={generateTasksForExisting}
            disabled={isGenerating}
          >
            <RefreshCw className={`h-4 w-4 mr-2 ${isGenerating ? 'animate-spin' : ''}`} />
            {isGenerating ? 'Generating...' : 'Generate Tasks'}
          </Button>
          <Button asChild>
            <Link href="/dashboard/tasks/new">
              <Plus className="h-4 w-4 mr-2" />
              Add Task
            </Link>
          </Button>
        </div>
      </div>

      {generateMessage && (
        <div className="bg-green-50 text-green-700 p-4 rounded-lg border border-green-200">
          {generateMessage}
        </div>
      )}

      {error && (
        <div className="bg-destructive/10 text-destructive p-4 rounded-lg">
          {error}
        </div>
      )}

      {/* Filters */}
      <div className="flex flex-wrap gap-4 items-center">
        <div className="flex items-center gap-2">
          <Filter className="h-4 w-4 text-gray-500" />
          <span className="text-sm text-gray-600">Filter:</span>
        </div>
        <div className="flex gap-2">
          {STATUS_FILTERS.map((filter) => (
            <button
              key={filter.value}
              onClick={() => setStatusFilter(filter.value)}
              className={`px-3 py-1.5 rounded-lg text-sm font-medium transition-colors ${
                statusFilter === filter.value
                  ? "bg-primary text-primary-foreground"
                  : "bg-gray-100 text-gray-700 hover:bg-gray-200"
              }`}
            >
              {filter.label}
            </button>
          ))}
        </div>
        <select
          value={categoryFilter}
          onChange={(e) => setCategoryFilter(e.target.value)}
          className="px-3 py-1.5 rounded-lg text-sm border bg-white text-gray-900"
        >
          {CATEGORIES.map((cat) => (
            <option key={cat.value} value={cat.value}>
              {cat.label}
            </option>
          ))}
        </select>
      </div>

      {/* Task Summary */}
      <div className="grid gap-4 md:grid-cols-4">
        <Card>
          <CardContent className="pt-6">
            <div className="text-center">
              <p className="text-2xl font-bold">{tasks.length}</p>
              <p className="text-sm text-gray-600">Total Tasks</p>
            </div>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="pt-6">
            <div className="text-center">
              <p className="text-2xl font-bold text-yellow-600">
                {pendingTasks.length}
              </p>
              <p className="text-sm text-gray-600">Pending</p>
            </div>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="pt-6">
            <div className="text-center">
              <p className="text-2xl font-bold text-blue-600">
                {inProgressTasks.length}
              </p>
              <p className="text-sm text-gray-600">In Progress</p>
            </div>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="pt-6">
            <div className="text-center">
              <p className="text-2xl font-bold text-green-600">
                {completedTasks.length}
              </p>
              <p className="text-sm text-gray-600">Completed</p>
            </div>
          </CardContent>
        </Card>
      </div>

      {/* Batches View */}
      {viewMode === "batches" && batches && (
        <div className="space-y-6">
          {/* Crops Section */}
          {batches.crops.length > 0 && (
            <div>
              <h2 className="text-lg font-semibold flex items-center gap-2 mb-4">
                <Wheat className="h-5 w-5 text-green-600" />
                Crop Batches ({batches.crops.length})
              </h2>
              <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">
                {batches.crops.map((batch) => (
                  <Card
                    key={batch.id}
                    className={`cursor-pointer hover:shadow-md transition-shadow ${
                      batch.overdueTasks > 0 ? "border-red-200" : ""
                    }`}
                    onClick={() => setSelectedBatch(batch)}
                  >
                    <CardContent className="pt-4">
                      <div className="flex items-start justify-between mb-3">
                        <div>
                          <h3 className="font-semibold text-gray-900">{batch.name}</h3>
                          {batch.plotName && (
                            <p className="text-sm text-gray-500">{batch.plotName}</p>
                          )}
                          {batch.farmName && (
                            <p className="text-xs text-gray-400">{batch.farmName}</p>
                          )}
                        </div>
                        <div className="h-10 w-10 rounded-full bg-green-100 flex items-center justify-center">
                          <Wheat className="h-5 w-5 text-green-600" />
                        </div>
                      </div>
                      
                      {/* Progress Bar */}
                      <div className="mb-3">
                        <div className="flex justify-between text-xs mb-1">
                          <span className="text-gray-500">Progress</span>
                          <span className="font-medium">{batch.progress}%</span>
                        </div>
                        <div className="w-full bg-gray-200 rounded-full h-2">
                          <div
                            className="bg-green-500 h-2 rounded-full"
                            style={{ width: `${batch.progress}%` }}
                          />
                        </div>
                      </div>
                      
                      {/* Task Stats */}
                      <div className="flex justify-between text-sm">
                        <span className="text-gray-500">
                          {batch.pendingTasks} pending
                        </span>
                        {batch.overdueTasks > 0 && (
                          <span className="text-red-600 font-medium">
                            {batch.overdueTasks} overdue
                          </span>
                        )}
                        <span className="text-green-600">
                          {batch.completedTasks} done
                        </span>
                      </div>
                      
                      {/* Upcoming Tasks Preview */}
                      {batch.upcomingTasks.length > 0 && (
                        <div className="mt-3 pt-3 border-t">
                          <p className="text-xs text-gray-500 mb-2">Next tasks:</p>
                          {batch.upcomingTasks.slice(0, 2).map((task) => (
                            <div key={task.id} className="text-xs text-gray-700 truncate">
                              • {task.title}
                            </div>
                          ))}
                        </div>
                      )}
                      
                      <div className="mt-3 flex justify-end">
                        <span className="text-xs text-primary flex items-center gap-1">
                          View Tasks <ArrowRight className="h-3 w-3" />
                        </span>
                      </div>
                    </CardContent>
                  </Card>
                ))}
              </div>
            </div>
          )}

          {/* Livestock Section */}
          {batches.livestock.length > 0 && (
            <div>
              <h2 className="text-lg font-semibold flex items-center gap-2 mb-4">
                <Beef className="h-5 w-5 text-orange-600" />
                Livestock Batches ({batches.livestock.length})
              </h2>
              <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">
                {batches.livestock.map((batch) => (
                  <Card
                    key={batch.id}
                    className={`cursor-pointer hover:shadow-md transition-shadow ${
                      batch.overdueTasks > 0 ? "border-red-200" : ""
                    }`}
                    onClick={() => setSelectedBatch(batch)}
                  >
                    <CardContent className="pt-4">
                      <div className="flex items-start justify-between mb-3">
                        <div>
                          <h3 className="font-semibold text-gray-900">{batch.name}</h3>
                          {batch.batchName && (
                            <p className="text-sm text-gray-500">{batch.batchName}</p>
                          )}
                          {batch.quantity && (
                            <p className="text-xs text-gray-400">{batch.quantity} animals</p>
                          )}
                        </div>
                        <div className="h-10 w-10 rounded-full bg-orange-100 flex items-center justify-center">
                          <Beef className="h-5 w-5 text-orange-600" />
                        </div>
                      </div>
                      
                      <div className="mb-3">
                        <div className="flex justify-between text-xs mb-1">
                          <span className="text-gray-500">Progress</span>
                          <span className="font-medium">{batch.progress}%</span>
                        </div>
                        <div className="w-full bg-gray-200 rounded-full h-2">
                          <div
                            className="bg-orange-500 h-2 rounded-full"
                            style={{ width: `${batch.progress}%` }}
                          />
                        </div>
                      </div>
                      
                      <div className="flex justify-between text-sm">
                        <span className="text-gray-500">{batch.pendingTasks} pending</span>
                        {batch.overdueTasks > 0 && (
                          <span className="text-red-600 font-medium">{batch.overdueTasks} overdue</span>
                        )}
                        <span className="text-green-600">{batch.completedTasks} done</span>
                      </div>
                      
                      {batch.upcomingTasks.length > 0 && (
                        <div className="mt-3 pt-3 border-t">
                          <p className="text-xs text-gray-500 mb-2">Next tasks:</p>
                          {batch.upcomingTasks.slice(0, 2).map((task) => (
                            <div key={task.id} className="text-xs text-gray-700 truncate">
                              • {task.title}
                            </div>
                          ))}
                        </div>
                      )}
                      
                      <div className="mt-3 flex justify-end">
                        <span className="text-xs text-primary flex items-center gap-1">
                          View Tasks <ArrowRight className="h-3 w-3" />
                        </span>
                      </div>
                    </CardContent>
                  </Card>
                ))}
              </div>
            </div>
          )}

          {/* Aquaculture Section */}
          {batches.aquaculture.length > 0 && (
            <div>
              <h2 className="text-lg font-semibold flex items-center gap-2 mb-4">
                <Fish className="h-5 w-5 text-blue-600" />
                Aquaculture Batches ({batches.aquaculture.length})
              </h2>
              <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">
                {batches.aquaculture.map((batch) => (
                  <Card
                    key={batch.id}
                    className={`cursor-pointer hover:shadow-md transition-shadow ${
                      batch.overdueTasks > 0 ? "border-red-200" : ""
                    }`}
                    onClick={() => setSelectedBatch(batch)}
                  >
                    <CardContent className="pt-4">
                      <div className="flex items-start justify-between mb-3">
                        <div>
                          <h3 className="font-semibold text-gray-900">{batch.name}</h3>
                          {batch.fishSpecies && (
                            <p className="text-sm text-gray-500">{batch.fishSpecies}</p>
                          )}
                          {batch.farmName && (
                            <p className="text-xs text-gray-400">{batch.farmName}</p>
                          )}
                        </div>
                        <div className="h-10 w-10 rounded-full bg-blue-100 flex items-center justify-center">
                          <Fish className="h-5 w-5 text-blue-600" />
                        </div>
                      </div>
                      
                      <div className="mb-3">
                        <div className="flex justify-between text-xs mb-1">
                          <span className="text-gray-500">Progress</span>
                          <span className="font-medium">{batch.progress}%</span>
                        </div>
                        <div className="w-full bg-gray-200 rounded-full h-2">
                          <div
                            className="bg-blue-500 h-2 rounded-full"
                            style={{ width: `${batch.progress}%` }}
                          />
                        </div>
                      </div>
                      
                      <div className="flex justify-between text-sm">
                        <span className="text-gray-500">{batch.pendingTasks} pending</span>
                        {batch.overdueTasks > 0 && (
                          <span className="text-red-600 font-medium">{batch.overdueTasks} overdue</span>
                        )}
                        <span className="text-green-600">{batch.completedTasks} done</span>
                      </div>
                      
                      {batch.upcomingTasks.length > 0 && (
                        <div className="mt-3 pt-3 border-t">
                          <p className="text-xs text-gray-500 mb-2">Next tasks:</p>
                          {batch.upcomingTasks.slice(0, 2).map((task) => (
                            <div key={task.id} className="text-xs text-gray-700 truncate">
                              • {task.title}
                            </div>
                          ))}
                        </div>
                      )}
                      
                      <div className="mt-3 flex justify-end">
                        <span className="text-xs text-primary flex items-center gap-1">
                          View Tasks <ArrowRight className="h-3 w-3" />
                        </span>
                      </div>
                    </CardContent>
                  </Card>
                ))}
              </div>
            </div>
          )}

          {/* Empty State */}
          {batches.crops.length === 0 && batches.livestock.length === 0 && batches.aquaculture.length === 0 && (
            <Card>
              <CardContent className="py-12 text-center">
                <LayoutGrid className="h-12 w-12 mx-auto text-gray-400 mb-4" />
                <h3 className="text-lg font-medium text-gray-900 mb-2">No Active Batches</h3>
                <p className="text-gray-600 mb-4">
                  Add crops, livestock, or aquaculture entries to see their tasks here.
                </p>
                <div className="flex gap-2 justify-center">
                  <Button asChild variant="outline">
                    <Link href="/dashboard/crops/new">Add Crop</Link>
                  </Button>
                  <Button asChild variant="outline">
                    <Link href="/dashboard/livestock/new">Add Livestock</Link>
                  </Button>
                </div>
              </CardContent>
            </Card>
          )}
        </div>
      )}

      {/* Selected Batch Detail Modal */}
      {selectedBatch && (
        <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50 p-4">
          <Card className="w-full max-w-2xl max-h-[80vh] overflow-hidden">
            <CardHeader className="border-b">
              <div className="flex items-center justify-between">
                <div className="flex items-center gap-3">
                  <div className={`h-10 w-10 rounded-full flex items-center justify-center ${
                    selectedBatch.type === "crop" ? "bg-green-100" :
                    selectedBatch.type === "livestock" ? "bg-orange-100" : "bg-blue-100"
                  }`}>
                    {selectedBatch.type === "crop" && <Wheat className="h-5 w-5 text-green-600" />}
                    {selectedBatch.type === "livestock" && <Beef className="h-5 w-5 text-orange-600" />}
                    {selectedBatch.type === "aquaculture" && <Fish className="h-5 w-5 text-blue-600" />}
                  </div>
                  <div>
                    <CardTitle>{selectedBatch.name}</CardTitle>
                    <p className="text-sm text-gray-500">
                      {selectedBatch.plotName || selectedBatch.batchName || selectedBatch.fishSpecies}
                    </p>
                  </div>
                </div>
                <Button variant="ghost" size="icon" onClick={() => setSelectedBatch(null)}>
                  ✕
                </Button>
              </div>
            </CardHeader>
            <CardContent className="p-4 overflow-y-auto max-h-[60vh]">
              <div className="grid grid-cols-3 gap-4 mb-4">
                <div className="text-center p-3 bg-yellow-50 rounded-lg">
                  <p className="text-2xl font-bold text-yellow-600">{selectedBatch.pendingTasks}</p>
                  <p className="text-xs text-gray-600">Pending</p>
                </div>
                <div className="text-center p-3 bg-red-50 rounded-lg">
                  <p className="text-2xl font-bold text-red-600">{selectedBatch.overdueTasks}</p>
                  <p className="text-xs text-gray-600">Overdue</p>
                </div>
                <div className="text-center p-3 bg-green-50 rounded-lg">
                  <p className="text-2xl font-bold text-green-600">{selectedBatch.completedTasks}</p>
                  <p className="text-xs text-gray-600">Completed</p>
                </div>
              </div>
              
              <h4 className="font-medium mb-3">Upcoming Tasks</h4>
              {selectedBatch.upcomingTasks.length > 0 ? (
                <div className="space-y-2">
                  {selectedBatch.upcomingTasks.map((task) => (
                    <div key={task.id} className="flex items-center justify-between p-3 bg-gray-50 rounded-lg">
                      <div>
                        <p className="font-medium text-sm">{task.title}</p>
                        <p className="text-xs text-gray-500">
                          Due: {new Date(task.dueDate).toLocaleDateString()}
                        </p>
                      </div>
                      <span className={`px-2 py-1 rounded text-xs ${PRIORITY_COLORS[task.priority]}`}>
                        {task.priority}
                      </span>
                    </div>
                  ))}
                </div>
              ) : (
                <p className="text-gray-500 text-sm">No upcoming tasks</p>
              )}
              
              <div className="mt-4 flex gap-2">
                <Button asChild className="flex-1">
                  <Link href={`/dashboard/${selectedBatch.type === "crop" ? "crops" : selectedBatch.type === "livestock" ? "livestock" : "aquaculture"}/${selectedBatch.id}`}>
                    View {selectedBatch.type === "crop" ? "Crop" : selectedBatch.type === "livestock" ? "Livestock" : "Pond"} Details
                  </Link>
                </Button>
                <Button variant="outline" onClick={() => {
                  setCategoryFilter(selectedBatch.type === "crop" ? "CROP" : selectedBatch.type === "livestock" ? "LIVESTOCK" : "AQUACULTURE");
                  setViewMode("list");
                  setSelectedBatch(null);
                }}>
                  View All Tasks
                </Button>
              </div>
            </CardContent>
          </Card>
        </div>
      )}

      {/* Calendar View */}
      {viewMode === "calendar" && (
        <Card>
          <CardHeader className="pb-2">
            <div className="flex items-center justify-between">
              <CardTitle>
                {currentMonth.toLocaleDateString("en-US", { month: "long", year: "numeric" })}
              </CardTitle>
              <div className="flex gap-1">
                <Button variant="outline" size="icon" onClick={prevMonth}>
                  <ChevronLeft className="h-4 w-4" />
                </Button>
                <Button variant="outline" size="icon" onClick={nextMonth}>
                  <ChevronRight className="h-4 w-4" />
                </Button>
              </div>
            </div>
          </CardHeader>
          <CardContent>
            <div className="grid grid-cols-7 gap-1">
              {["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"].map((day) => (
                <div key={day} className="text-center text-xs font-medium text-gray-500 py-2">
                  {day}
                </div>
              ))}
              {calendarDays.map((day, index) => {
                if (!day) {
                  return <div key={`empty-${index}`} className="h-24 bg-gray-50 rounded" />;
                }
                const dayTasks = tasksByDate.get(day.toDateString()) || [];
                const isToday = day.toDateString() === new Date().toDateString();
                const hasOverdue = dayTasks.some((t) => isOverdue(t.dueDate, t.status));
                
                return (
                  <div
                    key={day.toISOString()}
                    className={`h-24 border rounded p-1 overflow-hidden ${
                      isToday ? "border-primary bg-primary/5" : "border-gray-200"
                    } ${hasOverdue ? "bg-red-50" : ""}`}
                  >
                    <div className={`text-xs font-medium mb-1 ${isToday ? "text-primary" : "text-gray-700"}`}>
                      {day.getDate()}
                    </div>
                    <div className="space-y-0.5 overflow-y-auto max-h-16">
                      {dayTasks.slice(0, 3).map((task) => (
                        <div
                          key={task.id}
                          className={`text-xs px-1 py-0.5 rounded truncate cursor-pointer ${
                            task.status === "COMPLETED"
                              ? "bg-green-100 text-green-700 line-through"
                              : task.priority === "URGENT"
                              ? "bg-red-100 text-red-700"
                              : task.priority === "HIGH"
                              ? "bg-orange-100 text-orange-700"
                              : "bg-blue-100 text-blue-700"
                          }`}
                          title={task.title}
                          onClick={() => updateTaskStatus(task.id, task.status === "COMPLETED" ? "PENDING" : "COMPLETED")}
                        >
                          {task.title}
                        </div>
                      ))}
                      {dayTasks.length > 3 && (
                        <div className="text-xs text-gray-500 px-1">
                          +{dayTasks.length - 3} more
                        </div>
                      )}
                    </div>
                  </div>
                );
              })}
            </div>
          </CardContent>
        </Card>
      )}

      {/* Tasks List */}
      {viewMode === "list" && tasks.length === 0 ? (
        <Card>
          <CardContent className="py-12 text-center">
            <Calendar className="h-12 w-12 mx-auto text-gray-400 mb-4" />
            <h3 className="text-lg font-medium text-gray-900 mb-2">
              No tasks found
            </h3>
            <p className="text-gray-600 mb-4">
              {statusFilter || categoryFilter
                ? "Try adjusting your filters"
                : "Create your first task to get started"}
            </p>
            <Button asChild>
              <Link href="/dashboard/tasks/new">
                <Plus className="h-4 w-4 mr-2" />
                Add Task
              </Link>
            </Button>
          </CardContent>
        </Card>
      ) : viewMode === "list" && tasks.length > 0 ? (
        <div className="space-y-3">
          {tasks.map((task) => (
            <Card
              key={task.id}
              className={`${
                isOverdue(task.dueDate, task.status)
                  ? "border-red-200 bg-red-50"
                  : ""
              }`}
            >
              <CardContent className="py-4">
                <div className="flex items-start gap-4">
                  {/* Status Toggle */}
                  <button
                    onClick={() =>
                      updateTaskStatus(
                        task.id,
                        task.status === "COMPLETED" ? "PENDING" : "COMPLETED"
                      )
                    }
                    className="mt-1 hover:scale-110 transition-transform"
                  >
                    {STATUS_ICONS[task.status]}
                  </button>

                  {/* Task Details */}
                  <div className="flex-1 min-w-0">
                    <div className="flex items-center gap-2 mb-1">
                      <h3
                        className={`font-medium ${
                          task.status === "COMPLETED"
                            ? "line-through text-gray-500"
                            : "text-gray-900"
                        }`}
                      >
                        {task.title}
                      </h3>
                      <span
                        className={`px-2 py-0.5 rounded text-xs font-medium ${
                          PRIORITY_COLORS[task.priority]
                        }`}
                      >
                        {task.priority}
                      </span>
                    </div>
                    {task.description && (
                      <p className="text-sm text-gray-600 mb-2 line-clamp-2">
                        {task.description}
                      </p>
                    )}
                    <div className="flex items-center gap-4 text-sm text-gray-500">
                      <span
                        className={`flex items-center gap-1 ${
                          isOverdue(task.dueDate, task.status)
                            ? "text-red-600 font-medium"
                            : ""
                        }`}
                      >
                        <Calendar className="h-3.5 w-3.5" />
                        {formatDate(task.dueDate)}
                        {isOverdue(task.dueDate, task.status) && " (Overdue)"}
                      </span>
                      <span className="px-2 py-0.5 bg-gray-100 rounded text-xs">
                        {task.category === "CROP" ? "🌾 Crop" : 
                         task.category === "LIVESTOCK" ? "🐄 Livestock" :
                         task.category.replace("_", " ")}
                      </span>
                      {task.isAutoGenerated && (
                        <span className="px-2 py-0.5 bg-purple-100 text-purple-700 rounded text-xs">
                          Auto-generated
                        </span>
                      )}
                      {task.sourceType && (
                        <span className="px-2 py-0.5 bg-blue-50 text-blue-600 rounded text-xs">
                          {task.sourceType.replace("_", " ")}
                        </span>
                      )}
                    </div>
                  </div>

                  {/* Actions */}
                  <div className="flex items-center gap-2">
                    {task.status !== "COMPLETED" && (
                      <select
                        value={task.status}
                        onChange={(e) =>
                          updateTaskStatus(task.id, e.target.value)
                        }
                        className="text-xs border rounded px-2 py-1 bg-white text-gray-900"
                      >
                        <option value="PENDING">Pending</option>
                        <option value="IN_PROGRESS">In Progress</option>
                        <option value="COMPLETED">Completed</option>
                      </select>
                    )}
                    <button
                      onClick={() => deleteTask(task.id)}
                      className="p-1.5 text-gray-400 hover:text-red-500 hover:bg-red-50 rounded"
                    >
                      <Trash2 className="h-4 w-4" />
                    </button>
                  </div>
                </div>
              </CardContent>
            </Card>
          ))}
        </div>
      ) : null}
    </div>
  );
}
